# Generated by Django 4.2.4 on 2023-08-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(default='Статья', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='Новость', max_length=10),
        ),
    ]
