# Generated by Django 4.2.4 on 2023-08-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_article_type_alter_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tittle',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(default='Статья', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='tittle',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(default='Новость', max_length=10),
        ),
    ]
